insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10001,'hosam','Learn spring framework',CURRENT_DATE(),false);
insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10002,'hosam','learn spring data',CURRENT_DATE(),false);
insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10003,'hosam','learn spring security',CURRENT_DATE(),false);
insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10004,'hosam','learn spring boot',CURRENT_DATE(),false);
insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10005,'hosam','learn spring cloud',CURRENT_DATE(),false);
insert into TODO  (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (10006,'hosam','Find a job',CURRENT_DATE(),false);
